Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Wodka")
Ingredient.create(name: "Sekt")
Ingredient.create(name: "Aperol")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Sparkling water")